### ISSUE TITLE
Transform Links

### ISSUE THREAD

**Issue by daxpedda** [zheland/readme-sync#1]
I wasn't able to readme-sync to do any transformation of links by default. Here a minimal example.

Cargo.toml:
```toml
[package]
name = "test-readme-sync"
version = "0.0.0"
edition = "2021"
publish = false
documentation = "https://docs.rs/test-readme-sync"
repository = "https://github.com/daxpedda/test-readme-sync"

[dev-dependencies]
readme-sync = "0.2"
```

lib.rs
```rust
//! Test
//! [`Test`]
//! [`Test`](crate::Test)
//! [Test]
//!
//! [Test]: crate::Test

pub struct Test;

#[test]
fn readme_sync_test() {
    use readme_sync::{assert_sync, CMarkDocs, CMarkReadme, Config, Package};

    let package = Package::from_path(env!("CARGO_MANIFEST_DIR").into()).unwrap();
    let config = Config::from_package_docs_rs_features(&package);
    let readme = CMarkReadme::from_package(&package).unwrap();
    let docs = CMarkDocs::from_package_and_config(&package, &config).unwrap();

    let readme = readme
        .remove_badges_paragraph()
        .remove_documentation_section()
        .remove_codeblock_tag("no_sync")
        .disallow_absolute_repository_blob_links()
        .unwrap()
        .use_absolute_repository_blob_urls()
        .unwrap();

    let docs = docs
        .increment_heading_levels()
        .add_package_title()
        .remove_codeblock_rust_test_tags()
        .use_default_codeblock_rust_tag()
        .remove_hidden_rust_code()
        .disallow_absolute_package_docs_links()
        .unwrap()
        .use_absolute_package_docs_urls()
        .unwrap();

    assert_sync(&readme, &docs);
}
```

README.md:
```markdown
# test-readme-sync

Test
[`Test`]
[`Test`](crate::Test)
[Test]

[Test]: crate::Test
```

I expected the test to fail, because of `use_absolute_package_docs_urls`, but it succeeds instead.
